
<br><br><br>

<div style="padding: 25px;">
    <ul DIR="rtl">
        <?php
        foreach ($this->stories as $story) {
            $storySteps = split(",",$story['staticImages']);  
            $storyWrite = split(",",$story['staticStep']); 
            $count=0;
     
        }
        foreach ($storySteps as $step){
            ?>
        
        <p> <?=$count+1?> )<?= $storyWrite[$count]?> </p>
        <img src="../../../images/story1/static/<?= $step ?>" width="300px" height="300px">
        <br>
                
        <?php
        $count++;
        }
        
        
        ?>


    </ul>
</div>   





