

<br><br>

<div class="carousel slide" id="carousel-765973">
    <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#carousel-765973">
        </li>
        <li data-slide-to="1" data-target="#carousel-765973">
        </li>
        <li data-slide-to="2" data-target="#carousel-765973">
        </li>
    </ol>
    <div class="carousel-inner">

        <div class="item active">
            <img alt="" src="<?= $this->baseUrl() ?>/images/story1/homeStory1.jpg" />	
        </div>

        <div class="item">
            <img alt="" src="<?= $this->baseUrl() ?>/images/story1/HomeBackground.jpg" />
        </div>
        <div class="item">
            <img alt="" src="<?= $this->baseUrl() ?>/images/story1/homeStory1.jpg" />
        </div>
    </div> <a class="left carousel-control" href="#carousel-765973" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-765973" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>
    

<div style="width:100%;margin: 5%">
    <div style="width:40%;float: left">
        <img alt="" style="width:100%;" src="<?= $this->baseUrl() ?>/images/story1/homeStory1.jpg" /> 
    </div>
    
    <div style="width:40%;float: left;margin: 2%" dir="rtl">
        <ul>
        <li>
         نحن مجموعة من الشباب نتطلع الي
 تطوير المجتمع ومقتنعون تماما بأن هذا        
لن يتم الا من خلال زرع              
 المفاهيم الصحيحة في الاطفال
 بعيدا عن الطرق التقليدية للتعليم
        </li>
        <li> 
            و بدأنا بالسلوكيات و تعريف الطفل بالاسعافات الاولية
        </li>
        </ul> 
    </div>
</div>

<div style="clear: both"></div>

<div style="width:100%;margin: 5%">
    <div style="width:40%; float: left">
        <img alt="" style="width:100%;" src="<?= $this->baseUrl() ?>/images/story1/homeStory1.jpg" /> 
    </div>
    
    <div style="width:40%;float: left;margin: 2%">
        <ul>
        <li>
            ينقسم الموقع الي جزء لاولياء الامور
            و جزء خاص بالطفل
        </li>
        <li> 
            <strong>الجزء الخاص بالطفل</strong></br>
            يستطيع الطفل مشاهدة قصص توصل له معلومة مفيدة
            
            
            <br><strong>الجزء الخاص باولياء الامور</strong></br>
            يستطيعون متابعة كل القصص التي يشاهدها ابنائهم 
            و تقييم ما يقدمه الموقع و كذلك تقييم مدي تأثير الموقع في الطفل
               
        </li>
        </ul> 
    </div>
</div>